services:
  gmi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: gmi-image
    container_name: gmi-container
    volumes:
      - .:/gmi_base
    working_dir: /gmi_base
    environment:
      - PYTHONPATH=/gmi_base
    # Enable GPU support if available
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 