_target_: gmi.linear_operator.invertible_composite.InvertibleCompositeLinearOperator
matrix_operators:
  - _target_: gmi.linear_operator.scalar.ScalarLinearOperator
    scalar: 2.0
  - _target_: gmi.linear_operator.scalar.ScalarLinearOperator
    scalar: 3.0 