#!/bin/bash

# Run all modular studies using the CLI (gmi train-image-reconstructor) - Unrolled version
# This script runs all 27 studies with explicit CLI calls for each combination

CONFIG_DIR="examples/modular_configs"
OUTPUT_DIR="examples/modular_configs/outputs"

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo "🚀 Running all 27 modular studies (CLI unrolled version)"
echo "📁 Output directory: $OUTPUT_DIR"
echo "📊 Total studies: 27 (3 datasets x 3 noise levels x 3 reconstructors)"
echo ""

# MNIST studies (1 channel)
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/mnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/low_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/simple_cnn_1ch.yaml --device cuda --experiment-name "mnist_low_noise_simple_cnn_1ch"  # MNIST + low_noise + simple_cnn_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/mnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/low_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/linear_conv_1ch.yaml --device cuda --experiment-name "mnist_low_noise_linear_conv_1ch"  # MNIST + low_noise + linear_conv_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/mnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/low_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/diffusers_unet_28_1ch.yaml --device cuda --experiment-name "mnist_low_noise_diffusers_unet_28_1ch"  # MNIST + low_noise + diffusers_unet_28_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/mnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/medium_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/simple_cnn_1ch.yaml --device cuda --experiment-name "mnist_medium_noise_simple_cnn_1ch"  # MNIST + medium_noise + simple_cnn_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/mnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/medium_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/linear_conv_1ch.yaml --device cuda --experiment-name "mnist_medium_noise_linear_conv_1ch"  # MNIST + medium_noise + linear_conv_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/mnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/medium_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/diffusers_unet_28_1ch.yaml --device cuda --experiment-name "mnist_medium_noise_diffusers_unet_28_1ch"  # MNIST + medium_noise + diffusers_unet_28_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/mnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/high_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/simple_cnn_1ch.yaml --device cuda --experiment-name "mnist_high_noise_simple_cnn_1ch"  # MNIST + high_noise + simple_cnn_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/mnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/high_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/linear_conv_1ch.yaml --device cuda --experiment-name "mnist_high_noise_linear_conv_1ch"  # MNIST + high_noise + linear_conv_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/mnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/high_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/diffusers_unet_28_1ch.yaml --device cuda --experiment-name "mnist_high_noise_diffusers_unet_28_1ch"  # MNIST + high_noise + diffusers_unet_28_1ch

# BloodMNIST studies (3 channels)
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/bloodmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/low_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/simple_cnn_3ch.yaml --device cuda --experiment-name "bloodmnist_low_noise_simple_cnn_3ch"  # BloodMNIST + low_noise + simple_cnn_3ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/bloodmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/low_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/linear_conv_3ch.yaml --device cuda --experiment-name "bloodmnist_low_noise_linear_conv_3ch"  # BloodMNIST + low_noise + linear_conv_3ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/bloodmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/low_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/diffusers_unet_28_3ch.yaml --device cuda --experiment-name "bloodmnist_low_noise_diffusers_unet_28_3ch"  # BloodMNIST + low_noise + diffusers_unet_28_3ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/bloodmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/medium_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/simple_cnn_3ch.yaml --device cuda --experiment-name "bloodmnist_medium_noise_simple_cnn_3ch"  # BloodMNIST + medium_noise + simple_cnn_3ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/bloodmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/medium_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/linear_conv_3ch.yaml --device cuda --experiment-name "bloodmnist_medium_noise_linear_conv_3ch"  # BloodMNIST + medium_noise + linear_conv_3ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/bloodmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/medium_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/diffusers_unet_28_3ch.yaml --device cuda --experiment-name "bloodmnist_medium_noise_diffusers_unet_28_3ch"  # BloodMNIST + medium_noise + diffusers_unet_28_3ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/bloodmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/high_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/simple_cnn_3ch.yaml --device cuda --experiment-name "bloodmnist_high_noise_simple_cnn_3ch"  # BloodMNIST + high_noise + simple_cnn_3ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/bloodmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/high_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/linear_conv_3ch.yaml --device cuda --experiment-name "bloodmnist_high_noise_linear_conv_3ch"  # BloodMNIST + high_noise + linear_conv_3ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/bloodmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/high_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/diffusers_unet_28_3ch.yaml --device cuda --experiment-name "bloodmnist_high_noise_diffusers_unet_28_3ch"  # BloodMNIST + high_noise + diffusers_unet_28_3ch

# ChestMNIST studies (1 channel)
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/chestmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/low_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/simple_cnn_1ch.yaml --device cuda --experiment-name "chestmnist_low_noise_simple_cnn_1ch"  # ChestMNIST + low_noise + simple_cnn_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/chestmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/low_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/linear_conv_1ch.yaml --device cuda --experiment-name "chestmnist_low_noise_linear_conv_1ch"  # ChestMNIST + low_noise + linear_conv_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/chestmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/low_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/diffusers_unet_28_1ch.yaml --device cuda --experiment-name "chestmnist_low_noise_diffusers_unet_28_1ch"  # ChestMNIST + low_noise + diffusers_unet_28_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/chestmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/medium_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/simple_cnn_1ch.yaml --device cuda --experiment-name "chestmnist_medium_noise_simple_cnn_1ch"  # ChestMNIST + medium_noise + simple_cnn_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/chestmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/medium_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/linear_conv_1ch.yaml --device cuda --experiment-name "chestmnist_medium_noise_linear_conv_1ch"  # ChestMNIST + medium_noise + linear_conv_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/chestmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/medium_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/diffusers_unet_28_1ch.yaml --device cuda --experiment-name "chestmnist_medium_noise_diffusers_unet_28_1ch"  # ChestMNIST + medium_noise + diffusers_unet_28_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/chestmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/high_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/simple_cnn_1ch.yaml --device cuda --experiment-name "chestmnist_high_noise_simple_cnn_1ch"  # ChestMNIST + high_noise + simple_cnn_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/chestmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/high_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/linear_conv_1ch.yaml --device cuda --experiment-name "chestmnist_high_noise_linear_conv_1ch"  # ChestMNIST + high_noise + linear_conv_1ch
gmi train-image-reconstructor $CONFIG_DIR/training_config.yaml --train-dataset $CONFIG_DIR/datasets/chestmnist_train.yaml --measurement-simulator $CONFIG_DIR/measurement_simulators/high_noise.yaml --image-reconstructor $CONFIG_DIR/image_reconstructors/diffusers_unet_28_1ch.yaml --device cuda --experiment-name "chestmnist_high_noise_diffusers_unet_28_1ch"  # ChestMNIST + high_noise + diffusers_unet_28_1ch

echo ""
echo "============================================================"
echo "All 27 studies completed!"
echo "📁 Results saved to: $OUTPUT_DIR"
echo "============================================================" 