# Training configuration for modular experiments
# Optimized for fast training of 27 studies (3x3x3)

# Experiment name (used for output directories and logging)
experiment_name: "default_mnist_linear_conv"

# Default components (can be overridden by command line arguments)
train_dataset:
  class: gmi.datasets.MNIST
  params:
    train: true
    images_only: true

validation_dataset:
  class: gmi.datasets.MNIST
  params:
    train: false  # Use test split for validation
    images_only: true

test_dataset:
  class: gmi.datasets.MNIST
  params:
    train: false  # Use test split for test
    images_only: true

measurement_simulator:
  class: gmi.random_variable.gaussian.AdditiveWhiteGaussianNoise
  params:
    noise_standard_deviation: 0.05

image_reconstructor:
  class: gmi.network.LinearConv
  params:
    in_channels: 1
    out_channels: 1
    kernel_size: 7

# Training parameters
training:
  # Training for convergence
  num_epochs: 1000  # Reduced for quick testing
  num_iterations_train: 100  # Reduced for speed
  num_iterations_val: 10  # Increased for more stable validation loss
  num_iterations_test: 1  # Increased for better test evaluation
  final_test_iterations: 'all'  # Run final test on full test dataset
  learning_rate: 1e-3  # Reduced to 1e-4 for better convergence
  device: "cuda"  # or "cpu"
  
  # DataLoader parameters
  batch_size: 256  # Smaller for memory efficiency
  num_workers: 2
  shuffle_train: true
  shuffle_val: true
  shuffle_test: false
  
  # Advanced training features
  use_ema: true
  ema_decay: 0.999
  early_stopping: true
  patience: 50  # Increased for convergence-based early stopping
  val_loss_smoothing: 0.5  # Increased smoothing for more stable validation loss
  min_delta: 1e-6  # Slightly increased minimum change threshold
  
  # Validation and test parameters
  
  # Final evaluation parameters
  final_test_iterations: 20  # Reduced for speed
  
  # Test plotting parameters
  test_plot_vmin: 0
  test_plot_vmax: 1
  test_save_plots: true
  
  # Logging and monitoring
  verbose: true
  very_verbose: false
  wandb_project: "gmi-modular-studies"  # Enable WandB logging
  wandb_config: null
  
  # Model saving
  save_checkpoints: true 