_target_: gmi.linear_system.invertible_composite.InvertibleCompositeLinearSystem
matrix_operators:
  - _target_: gmi.linear_system.scalar.Scalar
    scalar: 2.0
  - _target_: gmi.linear_system.scalar.Scalar
    scalar: 3.0 